-- =============================================================================
-- Validator Mode — PostgreSQL Schema
-- =============================================================================
-- Extends the random-walk schema with tables for tandem crawl / validator mode.
-- Validators process pending edges via HTTP (t.me/<username>) instead of
-- SearchPublicChat, avoiding account-level Telegram rate limits.
--
-- Depends on: random-walk-schema.sql (edge_records, page_buffer, seed_channels,
--             invalid_channels)
-- =============================================================================


-- ---------------------------------------------------------------------------
-- pending_edge_batches
-- One row per source channel crawled in tandem mode.  Created when the first
-- potential edge is found; closed when the crawler finishes the channel.
-- Validators claim closed batches for walkback processing.
-- ---------------------------------------------------------------------------
CREATE TABLE pending_edge_batches (
    batch_id       VARCHAR(36)  PRIMARY KEY,      -- UUID generated by crawler
    crawl_id       VARCHAR(64)  NOT NULL,
    source_channel VARCHAR(64)  NOT NULL,
    source_page_id VARCHAR(36)  NOT NULL,         -- parent_id for next page_buffer insert
    source_depth   INTEGER      NOT NULL,         -- next page depth = source_depth + 1
    sequence_id    VARCHAR(36)  NOT NULL DEFAULT '',
    status         VARCHAR(16)  NOT NULL DEFAULT 'open',
    -- 'open'       = crawler still writing edges
    -- 'closed'     = crawler finished channel; all edges written
    -- 'processing' = validator claimed for walkback decision
    -- 'completed'  = walkback done, edge_records + page_buffer written
    attempt_count  INTEGER      NOT NULL DEFAULT 0,   -- incremented each time batch is claimed; poison detection
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    closed_at      TIMESTAMP,                         -- set when crawler finishes channel
    claimed_at     TIMESTAMPTZ,                       -- set/reset each time validator claims batch
    completed_at   TIMESTAMP                          -- set when validator finishes walkback
);

-- Validator polls for closed batches ready for walkback (FIFO)
CREATE INDEX idx_pending_batches_status
    ON pending_edge_batches (status, created_at);

-- Crawler polls to check if validator has outstanding work
CREATE INDEX idx_pending_batches_crawl_incomplete
    ON pending_edge_batches (crawl_id)
    WHERE status <> 'completed';


-- ---------------------------------------------------------------------------
-- pending_edges
-- One row per extracted username.  Written individually by the crawler as
-- edges are discovered (streaming).  Validators claim rows via
-- SELECT ... FOR UPDATE SKIP LOCKED.
-- ---------------------------------------------------------------------------
CREATE TABLE pending_edges (
    pending_id          SERIAL       PRIMARY KEY,
    batch_id            VARCHAR(36)  NOT NULL REFERENCES pending_edge_batches(batch_id),
    crawl_id            VARCHAR(64)  NOT NULL,
    destination_channel VARCHAR(64)  NOT NULL,
    source_channel      VARCHAR(64)  NOT NULL,
    sequence_id         VARCHAR(36)  NOT NULL DEFAULT '',
    discovery_time      TIMESTAMP    NOT NULL DEFAULT NOW(),
    source_type         VARCHAR(16)  NOT NULL DEFAULT '',
    -- 'mention' | 'text_url' | 'url' | 'plaintext' | ''
    validation_status   VARCHAR(16)  NOT NULL DEFAULT 'pending',
    -- 'pending' | 'validating' | 'valid' | 'not_channel' | 'invalid' | 'already_discovered'
    validation_reason   VARCHAR(64)  NOT NULL DEFAULT '',
    -- '' | 'not_supergroup' | 'not_found'
    validated_at        TIMESTAMP
);

-- Validator fetches edges by batch after claiming a walkback batch
CREATE INDEX idx_pending_edges_batch
    ON pending_edges (batch_id);

-- Validator claims pending edges for streaming validation (FIFO)
CREATE INDEX idx_pending_edges_pending
    ON pending_edges (discovery_time)
    WHERE validation_status = 'pending';


-- ---------------------------------------------------------------------------
-- source_type_stats
-- Aggregated hit/miss counts per source type per crawl.  Written by the
-- validator when completing each batch.  Provides transparency into which
-- extraction methods produce the most false positives.
-- ---------------------------------------------------------------------------
CREATE TABLE source_type_stats (
    crawl_id           VARCHAR(64) NOT NULL,
    source_type        VARCHAR(16) NOT NULL,
    total              INTEGER     NOT NULL DEFAULT 0,
    valid              INTEGER     NOT NULL DEFAULT 0,
    not_channel        INTEGER     NOT NULL DEFAULT 0,
    invalid            INTEGER     NOT NULL DEFAULT 0,
    already_discovered INTEGER     NOT NULL DEFAULT 0,
    PRIMARY KEY (crawl_id, source_type)
);


-- ---------------------------------------------------------------------------
-- discovered_channels
-- DB-backed first-discovery dedup.  Used by validators to enforce exactly-once
-- discovery across all pods within a crawl.  The composite PRIMARY KEY on
-- (channel_username, crawl_id) serialises concurrent INSERT ... ON CONFLICT
-- so exactly one validator wins per channel per crawl.
-- ---------------------------------------------------------------------------
CREATE TABLE discovered_channels (
    channel_username VARCHAR(64)  NOT NULL,
    crawl_id         VARCHAR(64)  NOT NULL,
    discovered_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (channel_username, crawl_id)
);


-- =============================================================================
-- GRANTS
-- =============================================================================

-- crawler_app (runtime DAPR binding user)
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pending_edge_batches TO crawler_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pending_edges         TO crawler_app;
GRANT SELECT, INSERT, UPDATE        ON TABLE source_type_stats     TO crawler_app;
GRANT SELECT, INSERT                ON TABLE discovered_channels   TO crawler_app;

GRANT USAGE, SELECT ON SEQUENCE pending_edges_pending_id_seq TO crawler_app;

-- crawler_readonly (analytics / monitoring)
GRANT SELECT ON TABLE pending_edge_batches TO crawler_readonly;
GRANT SELECT ON TABLE pending_edges        TO crawler_readonly;
GRANT SELECT ON TABLE source_type_stats    TO crawler_readonly;
GRANT SELECT ON TABLE discovered_channels  TO crawler_readonly;


-- =============================================================================
-- MIGRATION STATEMENTS (existing deployments)
-- =============================================================================

-- CREATE TABLE IF NOT EXISTS pending_edge_batches (
--     batch_id       VARCHAR(36)  PRIMARY KEY,
--     crawl_id       VARCHAR(64)  NOT NULL,
--     source_channel VARCHAR(64)  NOT NULL,
--     source_page_id VARCHAR(36)  NOT NULL,
--     source_depth   INTEGER      NOT NULL,
--     sequence_id    VARCHAR(36)  NOT NULL DEFAULT '',
--     status         VARCHAR(16)  NOT NULL DEFAULT 'open',
--     created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
--     closed_at      TIMESTAMP,
--     completed_at   TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS pending_edges (
--     pending_id          SERIAL       PRIMARY KEY,
--     batch_id            VARCHAR(36)  NOT NULL REFERENCES pending_edge_batches(batch_id),
--     crawl_id            VARCHAR(64)  NOT NULL,
--     destination_channel VARCHAR(64)  NOT NULL,
--     source_channel      VARCHAR(64)  NOT NULL,
--     sequence_id         VARCHAR(36)  NOT NULL DEFAULT '',
--     discovery_time      TIMESTAMP    NOT NULL DEFAULT NOW(),
--     source_type         VARCHAR(16)  NOT NULL DEFAULT '',
--     validation_status   VARCHAR(16)  NOT NULL DEFAULT 'pending',
--     validation_reason   VARCHAR(64)  NOT NULL DEFAULT '',
--     validated_at        TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS source_type_stats (
--     crawl_id           VARCHAR(64) NOT NULL,
--     source_type        VARCHAR(16) NOT NULL,
--     total              INTEGER     NOT NULL DEFAULT 0,
--     valid              INTEGER     NOT NULL DEFAULT 0,
--     not_channel        INTEGER     NOT NULL DEFAULT 0,
--     invalid            INTEGER     NOT NULL DEFAULT 0,
--     already_discovered INTEGER     NOT NULL DEFAULT 0,
--     PRIMARY KEY (crawl_id, source_type)
-- );

-- CREATE TABLE IF NOT EXISTS discovered_channels (
--     channel_username VARCHAR(64)  NOT NULL,
--     crawl_id         VARCHAR(64)  NOT NULL,
--     discovered_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
--     PRIMARY KEY (channel_username, crawl_id)
-- );

-- CREATE INDEX IF NOT EXISTS idx_pending_batches_status ON pending_edge_batches (status, created_at);
-- CREATE INDEX IF NOT EXISTS idx_pending_batches_crawl_incomplete ON pending_edge_batches (crawl_id) WHERE status <> 'completed';
-- CREATE INDEX IF NOT EXISTS idx_pending_edges_batch ON pending_edges (batch_id);
-- CREATE INDEX IF NOT EXISTS idx_pending_edges_pending ON pending_edges (discovery_time) WHERE validation_status = 'pending';

-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pending_edge_batches TO crawler_app;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pending_edges         TO crawler_app;
-- GRANT SELECT, INSERT, UPDATE        ON TABLE source_type_stats     TO crawler_app;
-- GRANT SELECT, INSERT                ON TABLE discovered_channels   TO crawler_app;
-- GRANT USAGE, SELECT ON SEQUENCE pending_edges_pending_id_seq       TO crawler_app;
-- GRANT SELECT ON TABLE pending_edge_batches TO crawler_readonly;
-- GRANT SELECT ON TABLE pending_edges        TO crawler_readonly;
-- GRANT SELECT ON TABLE source_type_stats    TO crawler_readonly;
-- GRANT SELECT ON TABLE discovered_channels  TO crawler_readonly;
